/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.html"
  ],
  safelist: [
    "opacity-100",
    "opacity-0",
    "transform",
    "translate-y-0",
    "translate-y-4",
    "inline-flex",
    "items-center",
    "justify-center",
    "rounded-md",
    "border",
    "px-2",
    "py-0.5",
    "text-xs",
    "font-medium",
    "w-fit",
    "whitespace-nowrap",
    "shrink-0",
    "gap-1",
    "focus-visible:border-ring",
    "focus-visible:ring-ring/50",
    "focus-visible:ring-[3px]",
    "aria-invalid:ring-destructive/20",
    "dark:aria-invalid:ring-destructive/40",
    "aria-invalid:border-destructive",
    "transition-[color,box-shadow]",
    "overflow-hidden",
    "border-transparent",
    "bg-primary",
    "text-primary-foreground",
    "hover:bg-primary/90",
    "bg-secondary",
    "text-secondary-foreground",
    "bg-destructive",
    "text-white",
    "hover:bg-destructive/90",
    "focus-visible:ring-destructive/20",
    "dark:focus-visible:ring-destructive/40",
    "dark:bg-destructive/60",
    "text-foreground",
    "hover:bg-accent",
    "hover:text-accent-foreground"
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
